// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ProsesKirim(arg1, arg2) {
  return window['go']['spamin']['Spamin']['ProsesKirim'](arg1, arg2);
}

export function Scrape(arg1, arg2, arg3) {
  return window['go']['spamin']['Spamin']['Scrape'](arg1, arg2, arg3);
}

export function YukKirim(arg1) {
  return window['go']['spamin']['Spamin']['YukKirim'](arg1);
}
