// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ProsesKirim(arg1:string,arg2:string):Promise<void>;

export function Scrape(arg1:string,arg2:number,arg3:string):Promise<void>;

export function YukKirim(arg1:string):Promise<void>;
